# moods.py

# Define the mood options and associated descriptive tags for the AI prompt builder.
# The actual content will be generated by the AI.
MOOD_INFO = {
    "learn": {
        "name": "Learn Something New",
        "description_tag": "factual, educational, insightful"
    },
    "reflect": {
        "name": "Reflect & Reset",
        "description_tag": "calming, mindful, introspective, question-based"
    },
    "story": {
        "name": "Storytime",
        "description_tag": "narrative, engaging, short story, anecdote"
    },
    "humor": {
        "name": "Make Me Laugh",
        "description_tag": "joke, pun, funny fact, lighthearted"
    },
    "surprise": {
        "name": "Surprise Me!",
        "description_tag": "unexpected, creative, mix of styles, delightful"
    },
    
    # Special topic-based moods
    "custom": {
        "name": "Custom Topic",
        "description_tag": "specific topic, personalized content"
    }
}

# Helper function to get user-friendly mood names and provide fallback
def get_mood_details(mood_key):
    """
    Retrieves the details (name, description_tag) for a given mood key.
    Returns a dictionary with 'name' and 'description_tag'.
    Handles invalid keys gracefully.
    """
    default_mood = {
        "name": "Unknown Mood",
        "description_tag": "general, engaging content"
    }
    return MOOD_INFO.get(mood_key, default_mood)

# List of valid mood keys for easy validation
VALID_MOODS = list(MOOD_INFO.keys())